#!/bin/bash
#
# Recursively push/pull latest changes in parallel on currently 
# checked out git branch in all sub-directories
# of the given directory.
#
# Requires the gpush / gpull utilities
#
#
MAX_DEPTH=1
FAIL=0

function log() {
	printf "$*\n" >&2
}


if [ "$#" -gt 0 ];
then
	MAX_DEPTH=$1
	log "Using recursion MAX_DEPTH = $MAX_DEPTH"
fi

for d in $(find . -maxdepth $MAX_DEPTH -type d);
do
	if [ -e $d/.git ];
	then
		log "Pushing on active branch for $d/"
		pushd $d >/dev/null
		gpush &
		popd >/dev/null
	fi
done

# Wait for completion
for job in $(jobs -p);
do
	wait $job || let "FAIL+=1"
done

if [ "$FAIL" == "0" ];
then
	# All completed successfully
	log "All done."
else
	log "$FAIL git pushes failed."
fi

