#!/usr/bin/perl

use strict;
use warnings;

sub camel2underscore {
	my $out = $2;
	while ($out =~ s/([a-z]+)([A-Z]+[a-z]+)/lc($1) . "_" . lc($2)/eg) {}

	return lc($out);
}

while (<>) {
	$_ =~ s/\b([_][a-z]+)((?:[A-Z]+[a-z]+)+)\b/$1 . "_" . camel2underscore($2)/eg;
	print $_;
}
